// packages/react/src/my-dialog.tsx
import type { DialogComponentProps } from "@dialog-fn/core";

export const MyDialog = ({
  isOpen,
  data,
  onClose,
  onConfirm,
}: DialogComponentProps<{foo:string}, {bar:string}>) => {
  const handleConfirm = () =>{
    onConfirm({bar:'demo'});
  }
  return (
    <dialog open={isOpen}>
      <div>
        <h1>My Dialog</h1>
        <p>Is open: {isOpen?.toString()}</p>
        <p>Data: {JSON.stringify(data)}</p>
        <button onClick={onClose}>Close</button>
        <button onClick={handleConfirm}>Confirm</button>
      </div>
    </dialog>
  );
};

// packages/svelte/src/routes/my-dialog.svelte
<script>
    export let isOpen = false;
    export let data = {};
    export let onClose = () => {};
    /**
     * @param v {any}
     */
    export let onConfirm = (v) => {};



    const handleClose = ()=>{
        onClose()
    }


    const handleConfirm = () => {
        onConfirm({ custom:'foo-bar' })
    }
</script>


<dialog open={isOpen}>
    <div>
      <h1>My Dialog</h1>
      <p>Is open: {isOpen.toString()}</p>
      <p>Data: {JSON.stringify(data)}</p>
      <button on:click={handleClose}>Close</button>
      <button on:click={handleConfirm}>Confirm</button>
    </div>
  </dialog>
